[build]
  command = "CI= npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NODE_OPTIONS = "--max_old_space_size=4096"